In [46]:
import xgboost as xgb
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import precision_recall_fscore_support,accuracy_score,recall_score,confusion_matrix,precision_score,f1_score


In [17]:
def read_features(csv_path_prefix):
    train=pd.read_csv(csv_path_prefix+"train.csv")
    train_X=train.iloc[:,0:len(train.columns)-2]
    train_Y=train.Class.values
    val=pd.read_csv(csv_path_prefix+"val.csv")
    val_X=train.iloc[:,0:len(val.columns)-2]
    val_Y=train.Class.values
    return train_X,val_X,train_Y,val_Y
def print_metrics(Y,predictions):
    acc=accuracy_score(Y,predictions)
    war=recall_score(Y,predictions,average="weighted")
    wap=precision_score(Y,predictions,average="weighted")
    waf1=f1_score(Y,predictions,average="weighted")
    print("Accuracy: ",acc)
    print("Recall: ",war)
    print("Precision: ",wap)
    print("F1-Score: ",waf1)
    a=confusion_matrix(Y,predictions)
    print("{0:.2f}\t{1:.2f}\t{2:.2f}\t{3:.2f}".format(acc*100,war*100,wap*100,waf1*100))
    return a


In [49]:

train_75_X,val_75_X,train_75_Y,val_75_Y=read_features("features/gru/upsample_2layer_64_75_8")
train_60_X,val_60_X,train_60_Y,val_60_Y=read_features("features/gru/upsample_2layer_64_60_8")
train_45_X,val_45_X,train_45_Y,val_45_Y=read_features("features/gru/upsample_2layer_64_45_8")
train_30_X,val_30_X,train_30_Y,val_30_Y=read_features("features/gru/upsample_2layer_64_30_8")
# all Y's are same

train_X=np.concatenate((train_30_X,train_45_X,train_60_X,train_75_X),axis=1)
val_X=np.concatenate((val_30_X,val_45_X,val_60_X,val_75_X),axis=1)
dTrain=xgb.DMatrix(train_X,train_30_Y)
dVal=xgb.DMatrix(val_X,val_30_Y)
param = {
         'learning_rate': 0.01,
         'objective': 'multi:softmax', 'silent': True,
         'num_class':3,
         'tree_method':'gpu_hist',
         'eval_metric:':'mlogloss'}
num_round = 4000
bst = xgb.train(param, dTrain, num_round,evals=[(dTrain,'train'),(dVal,'val')], early_stopping_rounds=10)
predictions=bst.predict(dVal)
print_metrics(val_30_Y,predictions)

[0]	train-merror:0.195813	val-merror:0.195813
Multiple eval metrics have been passed: 'val-merror' will be used for early stopping.

Will train until val-merror hasn't improved in 10 rounds.
[1]	train-merror:0.183498	val-merror:0.183498
[2]	train-merror:0.183498	val-merror:0.183498
[3]	train-merror:0.183498	val-merror:0.183498
[4]	train-merror:0.185961	val-merror:0.185961
[5]	train-merror:0.183498	val-merror:0.183498
[6]	train-merror:0.181034	val-merror:0.181034
[7]	train-merror:0.178571	val-merror:0.178571
[8]	train-merror:0.17734	val-merror:0.17734
[9]	train-merror:0.183498	val-merror:0.183498
[10]	train-merror:0.162562	val-merror:0.162562
[11]	train-merror:0.153941	val-merror:0.153941
[12]	train-merror:0.140394	val-merror:0.140394
[13]	train-merror:0.142857	val-merror:0.142857
[14]	train-merror:0.144089	val-merror:0.144089
[15]	train-merror:0.144089	val-merror:0.144089
[16]	train-merror:0.14532	val-merror:0.14532
[17]	train-merror:0.135468	val-merror:0.135468
[18]	train-merror:0.131

array([[252,   0,   0],
       [  6, 260,  10],
       [  4,   6, 274]], dtype=int64)

In [51]:

train_75_X,val_75_X,train_75_Y,val_75_Y=read_features("features/gru/upsample_2layer_64_75_16")
train_60_X,val_60_X,train_60_Y,val_60_Y=read_features("features/gru/upsample_2layer_64_60_16")
train_45_X,val_45_X,train_45_Y,val_45_Y=read_features("features/gru/upsample_2layer_64_45_16")
train_30_X,val_30_X,train_30_Y,val_30_Y=read_features("features/gru/upsample_2layer_64_30_16")
# all Y's are same

train_X=np.concatenate((train_30_X,train_45_X,train_60_X,train_75_X),axis=1)
val_X=np.concatenate((val_30_X,val_45_X,val_60_X,val_75_X),axis=1)
dTrain=xgb.DMatrix(train_X,train_30_Y)
dVal=xgb.DMatrix(val_X,val_30_Y)
param = {
         'learning_rate': 0.01,
         'objective': 'multi:softmax', 'silent': True,
         'num_class':3,
         'tree_method':'gpu_hist',
         'eval_metric:':'merror'}
num_round = 4000
bst = xgb.train(param, dTrain, num_round,evals=[(dTrain,'train'),(dVal,'val')], early_stopping_rounds=10)
predictions=bst.predict(dVal)
print_metrics(val_30_Y,predictions)

[0]	train-merror:0.210591	val-merror:0.210591
Multiple eval metrics have been passed: 'val-merror' will be used for early stopping.

Will train until val-merror hasn't improved in 10 rounds.
[1]	train-merror:0.169951	val-merror:0.169951
[2]	train-merror:0.166256	val-merror:0.166256
[3]	train-merror:0.149015	val-merror:0.149015
[4]	train-merror:0.155172	val-merror:0.155172
[5]	train-merror:0.156404	val-merror:0.156404
[6]	train-merror:0.14532	val-merror:0.14532
[7]	train-merror:0.146552	val-merror:0.146552
[8]	train-merror:0.141626	val-merror:0.141626
[9]	train-merror:0.151478	val-merror:0.151478
[10]	train-merror:0.135468	val-merror:0.135468
[11]	train-merror:0.130542	val-merror:0.130542
[12]	train-merror:0.139163	val-merror:0.139163
[13]	train-merror:0.130542	val-merror:0.130542
[14]	train-merror:0.125616	val-merror:0.125616
[15]	train-merror:0.12069	val-merror:0.12069
[16]	train-merror:0.128079	val-merror:0.128079
[17]	train-merror:0.12069	val-merror:0.12069
[18]	train-merror:0.11822

array([[252,   0,   0],
       [  1, 269,   6],
       [  0,   8, 276]], dtype=int64)

In [59]:

train_75_X,val_75_X,train_75_Y,val_75_Y=read_features("features/lstm/upsample_2layer_64_75_8")
train_60_X,val_60_X,train_60_Y,val_60_Y=read_features("features/lstm/upsample_2layer_64_60_8")
train_45_X,val_45_X,train_45_Y,val_45_Y=read_features("features/lstm/upsample_2layer_64_45_8")
train_30_X,val_30_X,train_30_Y,val_30_Y=read_features("features/lstm/upsample_2layer_64_30_8")
# all Y's are same

train_X=np.concatenate((train_30_X,train_45_X,train_60_X,train_75_X),axis=1)
val_X=np.concatenate((val_30_X,val_45_X,val_60_X,val_75_X),axis=1)
dTrain=xgb.DMatrix(train_X,train_30_Y)
dVal=xgb.DMatrix(val_X,val_30_Y)
param = {
         'learning_rate': 0.01,
         'objective': 'multi:softmax', 'silent': True,
         'num_class':3,
         'tree_method':'gpu_hist',
         'eval_metric:':'merror'}
num_round = 4000
bst = xgb.train(param, dTrain, num_round,evals=[(dTrain,'train'),(dVal,'val')], early_stopping_rounds=10)

print_metrics(val_30_Y,predictions=bst.predict(dVal))

[0]	train-merror:0.167488	val-merror:0.167488
Multiple eval metrics have been passed: 'val-merror' will be used for early stopping.

Will train until val-merror hasn't improved in 10 rounds.
[1]	train-merror:0.149015	val-merror:0.149015
[2]	train-merror:0.141626	val-merror:0.141626
[3]	train-merror:0.14532	val-merror:0.14532
[4]	train-merror:0.135468	val-merror:0.135468
[5]	train-merror:0.139163	val-merror:0.139163
[6]	train-merror:0.141626	val-merror:0.141626
[7]	train-merror:0.1367	val-merror:0.1367
[8]	train-merror:0.139163	val-merror:0.139163
[9]	train-merror:0.134236	val-merror:0.134236
[10]	train-merror:0.133005	val-merror:0.133005
[11]	train-merror:0.12931	val-merror:0.12931
[12]	train-merror:0.121921	val-merror:0.121921
[13]	train-merror:0.119458	val-merror:0.119458
[14]	train-merror:0.118227	val-merror:0.118227
[15]	train-merror:0.109606	val-merror:0.109606
[16]	train-merror:0.108374	val-merror:0.108374
[17]	train-merror:0.110837	val-merror:0.110837
[18]	train-merror:0.099754	

array([[249,   3,   0],
       [  8, 258,  10],
       [  6,   6, 272]], dtype=int64)

In [58]:
print_metrics(train_30_Y,bst.predict(dTrain))

Accuracy:  0.9593596059113301
Recall:  0.9593596059113301
Precision:  0.9596197765498349
F1-Score:  0.9592597626034858
95.94	95.94	95.96	95.93


array([[249,   3,   0],
       [  8, 258,  10],
       [  6,   6, 272]], dtype=int64)

In [61]:

train_75_X,val_75_X,train_75_Y,val_75_Y=read_features("features/lstm/upsample_2layer_64_75_16")
train_60_X,val_60_X,train_60_Y,val_60_Y=read_features("features/lstm/upsample_2layer_64_60_16")
train_45_X,val_45_X,train_45_Y,val_45_Y=read_features("features/lstm/upsample_2layer_64_45_16")
train_30_X,val_30_X,train_30_Y,val_30_Y=read_features("features/lstm/upsample_2layer_64_30_16")
# all Y's are same

train_X=np.concatenate((train_30_X,train_45_X,train_60_X,train_75_X),axis=1)
val_X=np.concatenate((val_30_X,val_45_X,val_60_X,val_75_X),axis=1)
dTrain=xgb.DMatrix(train_X,train_30_Y)
dVal=xgb.DMatrix(val_X,val_30_Y)
param = {
         'learning_rate': 0.01,
         'objective': 'multi:softmax', 'silent': True,
         'num_class':3,
         'tree_method':'gpu_hist',
         'eval_metric:':'merror'}
num_round = 4000
bst = xgb.train(param, dTrain, num_round,evals=[(dTrain,'train'),(dVal,'val')], early_stopping_rounds=10)

print_metrics(val_30_Y,predictions=bst.predict(dVal))

[0]	train-merror:0.269704	val-merror:0.269704
Multiple eval metrics have been passed: 'val-merror' will be used for early stopping.

Will train until val-merror hasn't improved in 10 rounds.
[1]	train-merror:0.261084	val-merror:0.261084
[2]	train-merror:0.238916	val-merror:0.238916
[3]	train-merror:0.226601	val-merror:0.226601
[4]	train-merror:0.229064	val-merror:0.229064
[5]	train-merror:0.226601	val-merror:0.226601
[6]	train-merror:0.215517	val-merror:0.215517
[7]	train-merror:0.20936	val-merror:0.20936
[8]	train-merror:0.206897	val-merror:0.206897
[9]	train-merror:0.197044	val-merror:0.197044
[10]	train-merror:0.189655	val-merror:0.189655
[11]	train-merror:0.181034	val-merror:0.181034
[12]	train-merror:0.178571	val-merror:0.178571
[13]	train-merror:0.163793	val-merror:0.163793
[14]	train-merror:0.166256	val-merror:0.166256
[15]	train-merror:0.162562	val-merror:0.162562
[16]	train-merror:0.162562	val-merror:0.162562
[17]	train-merror:0.163793	val-merror:0.163793
[18]	train-merror:0.1

array([[231,  12,   9],
       [ 11, 244,  21],
       [  4,  10, 270]], dtype=int64)